#!/usr/bin/env php
<?php

use RipLogChecker\RipLogCheckerCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

$application = new Application('riplogchecker', '0.0.1');
$application->add(new RipLogCheckerCommand());
$application->run();